version: "3"
services:
  api:
    container_name: api
    build: ./0x-tracker-api
    command: sh -c "sleep 30 && npm start"
    restart: unless-stopped
    ports:
      - "3001:3001"
    networks:
      - metric-tracker-network
  worker:
    container_name: worker
    build: ./0x-tracker-worker
    command: sh -c "sleep 30 && npm start / nodemon"
    restart: unless-stopped
    networks:
      - metric-tracker-network
  event-extractor:
    container_name: event-extractor
    build: ./0x-event-extractor
    command: sh -c "sleep 30 && yarn start / nodemon"
    restart: unless-stopped
    networks:
      - metric-tracker-network
  mongo:
    container_name: mongo
    image: mongo
    ports:
    - "27017:27017"
    volumes:
    - mongo-data:/data/db
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo --quiet) -eq 1
      interval: 10s
      start_period: 30s
    command: ["--replSet", "0x-tracker-events"]
    restart: unless-stopped
    networks:
      - metric-tracker-network
  redis:
    container_name: redis
    image: "redis:alpine"
    restart: unless-stopped
    ports:
    - "6379:6379"
    volumes:
    - redis-data:/data
    networks:
      - metric-tracker-network
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data-01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - metric-tracker-network
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data-02:/usr/share/elasticsearch/data
    networks:
      - metric-tracker-network
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data-03:/usr/share/elasticsearch/data
    networks:
      - metric-tracker-network
networks:
  metric-tracker-network:
    driver: bridge
volumes:
  redis-data:
    driver: local
  es-data-01:
    driver: local
  es-data-02:
    driver: local
  es-data-03:
    driver: local
  mongo-data:
    driver: local
